services:
  - type: web
    name: allfinder-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_SEARCH_KEY
        sync: false
      - key: GOOGLE_SEARCH_ENGINE_ID
        sync: false
      - key: GOOGLE_MAPS_KEY
        sync: false
